version: '3.7'
services:
  application:
    container_name: app
    build: ../uppd-application
    image: uppd-app:la
    depends_on:
      - database
      - server
    ports:
      - '8080:80'
  server:
    container_name: tile_server
    build: ../uppd-tile-server
    image: tile-server:la
    depends_on:
      - database
    environment:
      DB_HOST: database
      DB_PASSWORD: changeMe
      DATABASE: uppd_data
      RETRY_COUNT: 12
      RETRY_WAIT: 5
    ports:
      - '8000:8000'
  database:
    container_name: database
    build: ../uppd-database
    image: database:la
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: uppd_data
    ports:
      - '5432:5432'
