CREATE SCHEMA uppd;
ALTER SCHEMA uppd OWNER TO postgres;
ALTER DATABASE uppd_data SET search_path to uppd, public;

CREATE ROLE admin SUPERUSER;
CREATE ROLE readwrite;
CREATE ROLE read;

-- *** CHANGE DEFAULT PASSWORDS BELOW IF DEPLOYING TO PRODUCTION ***
CREATE USER uppdadmin WITH ENCRYPTED PASSWORD 'changeMe';
CREATE USER uppdread WITH ENCRYPTED PASSWORD 'changeMe';
CREATE USER uppdreadwrite WITH ENCRYPTED PASSWORD 'changeMe';

ALTER USER postgres WITH ENCRYPTED PASSWORD 'changeMe';
 
GRANT admin TO uppdadmin;
GRANT readwrite TO uppdreadwrite;
GRANT read TO uppdread;

GRANT USAGE ON SCHEMA uppd to admin;
GRANT USAGE ON SCHEMA uppd to readwrite;
GRANT USAGE ON SCHEMA uppd to read;

ALTER DEFAULT PRIVILEGES IN SCHEMA uppd
  GRANT SELECT ON TABLES TO uppdread;
ALTER DEFAULT PRIVILEGES IN SCHEMA uppd
  GRANT SELECT ON SEQUENCES TO uppdread;
ALTER DEFAULT PRIVILEGES IN SCHEMA uppd
  GRANT SELECT, INSERT, UPDATE ON TABLES TO uppdreadwrite;
ALTER DEFAULT PRIVILEGES IN SCHEMA uppd
  GRANT SELECT, UPDATE ON SEQUENCES TO uppdreadwrite;
